-define(ELECTION_TIMEOUT_MIN, 250).
-define(ELECTION_TIMEOUT_MAX, 500).
-define(HEART_BEAT_TIMEOUT, 150).
-define(NODES, [node1@honeypot, node2@honeypot, node3@honeypot]).
-define(FSM_MODULE, kv_store).
