-define(ELECTION_TIMEOUT_MIN, 250).
-define(ELECTION_TIMEOUT_MAX, 500).
-define(HEART_BEAT_TIMEOUT, 150).
-define(NODES, [node1@unknown, node2@unknown, node3@unknown, erlang_rest_kv@unknown]).
-define(FSM_MODULE, kv_store).
